---
- name: 'Create go workspace'
  file:
    dest: "~/projects/go-workspace/{{ item }}"
    state: 'directory'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0700'
  with_items:
    - 'bin'
    - 'pkg'
    - "src/github.com/margueritepd"
    - "src/github.com/pagerduty"
    - "src/github.com/des4maisons"

- name: 'Install golang'
  homebrew:
    name: 'go'
