---
- name: 'Put all the bash-related config files in place'
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'
  with_items:
    - 'bash_profile'
    - 'profile'

- name: 'Symlink ~/.bashrc to managed bashrc'
  file:
    src: "{{ role_path }}/files/bashrc"
    dest: '~/.bashrc'
    state: 'link'
    force: 'yes'

- name: 'Ensure that these files do not exist'
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '~/.bash_login'

- name: 'Create ~/tmp'
  file:
    path: '~/tmp'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0700'
    state: 'directory'
