---
- hosts: all
  connection: local
  roles:
    - 'bash'
    - 'xdg'
    - 'i3'
    - 'vim'
    - 'tmux'
    - 'git'
    - 'symlinks'
    - 'ssh_config'

    - role: 'set_gsettings_value'
      schema: 'org.gnome.settings-daemon.plugins.keyboard'
      key: 'active'
      value: 'false'
      expected_value: 'false'
