---
- hosts: all
  connection: local
  roles:
    - 'bash'
    - 'vim'
    - 'tmux'
    - 'git'
    - 'apps'
    - 'mtrack'
  vars:
    mtrack_repo_path: "{{ '~/software/xf86-input-mtrack' | expanduser }}"
