---
- name: 'symlink ~/Dropbox/gnupg to ~/.gnupg'
  file:
    src: '~/Dropbox/gnupg'
    dest: '~/.gnupg'
    state: 'link'
    force: 'yes'

- name: 'symlink ~/Dropbox/projects to ~/projects'
  file:
    src: '~/Dropbox/projects'
    dest: '~/projects'
    state: 'link'
    force: 'yes'

- name: 'Create the ~/tmp directory'
  file:
    dest: '~/tmp'
    state: 'directory'
