---
- name: 'Install system apps'
  homebrew:
    name:
      - 'asdf'

- name: 'install asdf plugins'
  command: 'asdf plugin add {{ item }}'
  args:
    creates: '${HOME}/.asdf/plugins/{{ item }}'
  loop:
    - ruby
    - python
      #    - terraform
    - tflint
    - golang
    - terraform-docs
    - erlang
    - elixir
    - yarn
    - nodejs


- name: 'install some versions of things via asdf'
  command: 'asdf install {{ item.package }} {{ item.version }}'
  args:
    creates: '${HOME}/.asdf/installs/{{ item.package }}/{{ item.version }}'
  loop:
    - { package: 'ruby', version: '2.7.3' }
      #    - { package: 'terraform', version: '0.14.6' }
    #- { package: 'nodejs', version: '14.16.0' }
    - { package: 'yarn', version: '1.22.10' }
    #- { package: 'erlang', version: '23.1.1' }
    - { package: 'elixir', version: '1.11.1-otp-23' }
