---
- name: 'Put the git config files in place'
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'
  with_items:
    - 'gitignore_global'

- name: 'Create gitconfig'
  template:
    src: 'gitconfig'
    dest: '~/.gitconfig'
