---
- name: 'Put the git config files in place'
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  with_items:
    - 'gitconfig'
    - 'gitignore_global'
