---

- name: 'Check if brew executable is installed'
  stat:
    path: '/usr/local/bin/brew'
  register: brew

- name: 'Download homebrew installation script'
  get_url:
    url: 'https://raw.githubusercontent.com/Homebrew/install/master/install'
    dest: '/Users/{{ user }}/tmp/homebrew-install.rb'
  when: 'not brew.stat.exists'

- name: 'Install homebrew'
  command: 'ruby "/Users/{{ user }}/tmp/homebrew-install.rb"'
  args:
    creates: '/usr/local/bin/brew'
  register: 'install'
  failed_when: 'install.rc != 0 and "already installed" not in install.stderr'

- name: 'Update homebrew'
  homebrew:
    update_homebrew: true

- name: 'Update all homebrew packages'
  homebrew:
    upgrade_all: true
