---
- name: 'Install system apps'
  package:
    name:
      - 'jq'
      - 'libdvd-pkg'
      - 'ffmpeg'
      - 'vim'
      - 'curl'
      - 'ledger'
      - 'simple-scan'
      - 'gnome-tweaks' # to specify keyboard mappings?
      - 'xclip' # for pbcopy, pbpaste
      - 'audacity'
      - 'zoom'
      - 'gthumb'
  become: yes

- name: 'Install audacity'
  get_url:
    url: 'https://www.fosshub.com/Audacity.html?dwl=audacity-linux-3.1.3-x86_64.AppImage'
    dest: '{{ home }}/bin'
    mode: '0700'
