---
- name: 'Install system apps'
  package:
    name:
      - 'jq'
      - 'libdvd-pkg'
      - 'ffmpeg'
      - 'vim'
      - 'curl'
      - 'ledger'
      - 'simple-scan'
      - 'gnome-tweaks' # to specify keyboard mappings?
      - 'xclip' # for pbcopy, pbpaste
      - 'audacity'
      - 'zoom'
      - 'gthumb'
  become: yes

- name: 'Install audacity'
  community.general.snap:
    name:
      - 'audacity'
