---

- name: 'Install system apps'
  homebrew:
    name:
      - 'libxml2'
      - 'libxslt'
      - 'htop'
      - 'wget'
      - 'watch'
      - 'htop'
      - 'python3'
      - 'gpg'
      - 'jq'
      - 'coreutils'
      - 'awscli'
