---

- name: 'Install system apps'
  when: 'ansible_pkg_mgr == "brew"'
  homebrew:
    name:
      - 'libxml2'
      - 'libxslt'
      - 'htop'
      - 'wget'
      - 'watch'
      - 'python3'
      - 'gpg'
      - 'jq'
      - 'coreutils'
      - 'awscli'
      - 'pstree'
      - 'tree'
      - 'mtr'
      - 'jid'
      - 'kubectl'
      - 'k9s'
      - 'aws-okta'
      - 'docker-credentials-helper-ecr'
      - 'telnet'
      - 'bash-completion'

- name: 'Install system apps'
  when: 'ansible_pkg_mgr != "brew"'
  package:
    name:
      - 'jq'
      - 'libdvd-pkg'
  become: yes
