---
- name: 'Put the tmux.conf in place'
  copy:
    src: 'tmux.conf'
    dest: '~/.tmux.conf'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'

- name: 'Install tmux'
  homebrew:
    name: 'tmux'
