---
- name: 'Put the tmux.conf in place'
  copy:
    src: 'tmux.conf'
    dest: '~/.tmux.conf'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'

- name: 'Install tmux'
  when: 'ansible_pkg_mgr == "brew"'
  homebrew:
    name: 'tmux'

- name: 'Install tmux'
  when: 'ansible_pkg_mgr != "brew"'
  package:
    name: 'tmux'
  become: yes
