# vim: set filetype=sh :

export SBT_CREDENTIALS=$HOME/.sbt/credentials

# Source the .profile file, if it exists
[ -r ~/.profile ] && [ -f ~/.profile ] && source ~/.profile

# Source the .bashrc file, if it exists
[ -r ~/.bashrc ] && [ -f ~/.bashrc ] && source ~/.bashrc
