# vim: set filetype=sh :

#****************
# Shell options
#****************

# List all matches in case multiple possible completions are possible
set show-all-if-ambiguous on

# Do not autocomplete hidden files unless the pattern explicitly begins with a dot
set match-hidden-files off

# Show all autocomplete results at once
set page-completions off

# If there are more than 200 possible completions for a word, ask to show them all
set completion-query-items 200

# Show extra file information when completing, like `ls -F` does
set visible-stats on

# Be more intelligent when autocompleting by also looking at the text after
# the cursor. For example, when the current line is "cd ~/src/mozil", and
# the cursor is on the "z", pressing Tab will not autocomplete it to "cd
# ~/src/mozillail", but to "cd ~/src/mozilla". (This is supported by the
# Readline used by Bash 4.)
set skip-completed-text on

# Allow UTF-8 input and output, instead of showing stuff like $'\0123\0456'
set input-meta on
set output-meta on
set convert-meta off

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

shopt -s checkwinsize

#***************
# Bash Exports
#***************

# Set the terminal type to xterm-256color
export TERM=xterm-256color

# Make vim the default editor
export EDITOR="vim"

# Larger bash history
export HISTSIZE=2000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups:ignorespace
# Make some commands not show up in history
export HISTIGNORE="ls:cd:cd -:pwd:exit:date"

# Prefer US English and use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Highlight section titles in manual pages
export LESS_TERMCAP_md="$ORANGE"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Always enable colored `grep` output
export GREP_OPTIONS="--color=auto"

# Fancy ls colors
export CLICOLOR='Yes'
export LSCOLORS='ExGxCxDxBxegedabagacad'

# Prevent 'less' from
export LESS="-i -R"
export LESSHISTFILE='/dev/null'
export LESSHISTSIZE=0

#**************
# Homebrew
#**************

if type brew &>/dev/null; then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "$COMPLETION" ]] && source "$COMPLETION"
    done
  fi
fi

# only run `homebrew update` every week
export HOMEBREW_AUTO_UPDATE_SECS=604800

#***************
# asdf
#***************
if which brew > /dev/null; then
  . $(brew --prefix asdf)/libexec/asdf.sh
fi

# Autocompletion
if which foo > /dev/null; then
  source <(kubectl completion bash)
fi

#***************
# Bash Aliases
#***************

# git
alias g="git"
function git-home() {
  git config user.name 'des4maisons'
  git config user.email 'des4maisons+github@gmail.com'
}

alias cp='cp -i'
alias ls='ls -F'
alias mv='mv -i'
alias rm='rm -i'

# bundler
alias b="bundle exec"

# k8s
alias k=kubectl

# gpg
alias gpg-list-keys="gpg --list-keys"
alias gpg-encrypt="gpg --encrypt -a"
alias gpg-decrypt="gpg --decrypt"

# openssl / certificates
# show info about certificate signing request
alias req='openssl req -text -noout -in'
# show info (from CA) about certificate
alias cert='openssl x509 -text -noout -in'
# show info about a certificate key
alias key='openssl rsa -text -noout -in'

# desktop icons
alias desktop-clear='defaults write com.apple.finder CreateDesktop false && killall Finder'
alias desktop-restore='defaults write com.apple.finder CreateDesktop true && killall Finder'

# camera
alias camera-restart="sudo killall VDCAssistant"

# python
# when brew intsalls python3 it installs the symlinks to the binaries with a 3 at the end.
alias pip=pip3

# docker
alias dc=docker-compose


#************
# GPG agent
#************

if [ -f "${HOME}/.gnupg/gpg-agent-info" ]; then
  . "${HOME}/.gnupg/gpg-agent-info"
  export GPG_AGENT_INFO
  export SSH_AUTH_SOCK
fi

#***********
# Bash
#***********

# grab transcription from json output of Amazon Transcribe
function transcript ()
{
  local input_file="$1"
  jq -r '.results | .transcripts[].transcript' < "${input_file}"
}

#****************
# PS1
#****************

git_prompt_vars ()
{
    local ref=$(git symbolic-ref HEAD 2> /dev/null);
    SCM_BRANCH=${ref#refs/heads/};
    echo -e "$SCM_BRANCH"
}

make_color ()
{
    pre_color="\[\033[";
    post_color="m\]";
    echo -e "${pre_color}$1${post_color}"
}

blue=$(make_color "0;34")
purple=$(make_color "0;35")
reset=$(make_color "0;0")
green=$(make_color "0;32")

# when a process exits with nonzero status,
# show a sad face and the exit code
ps1_status ()
{
    local status=$?;
    if [ $status -ne 0 ]; then
        smiley=":(";
    else
        smiley=":)";
    fi;
    echo -e "$smiley $status"
}

PS1="\n${blue}\$(ps1_status) ${purple}\u @ \h ${reset}in ${green}\w\n| \$(git_prompt_vars) | $ ${reset}"
export PS1

PATH="$PATH:${HOME}/bin"
PATH="$PATH:/usr/sbin"
PATH="/usr/local/bin:$PATH"
PATH="/usr/local/sbin:$PATH"
PATH="$PATH:${HOME}/Library/Python/3.7/bin"
export PATH

# load rbenv shims
# if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

#### Golang
# For more info on GOPATH, see go help gopath
export GOPATH="${HOME}/projects/go-workspace"
PATH="${PATH}:${GOPATH}/bin"


#*************
# Sumo
#*************

sumo () {
  ( cd ~/.livetail; unbuffer ./livetail $@; )
}

#*************
# extras
#*************

[ -f ${HOME}/.bash_extras ] && . ${HOME}/.bash_extras
# OS-specific extras
[ -f ${HOME}/.bash_extras-os ] && . ${HOME}/.bash_extras-os

