---
- name: 'Create the ~/.vim directory'
  file:
    path: '~/.vim'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0700'
    state: directory

- name: 'Create the ~/.vim/bundle directory'
  file:
    path: '~/.vim/bundle'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0700'
    state: directory

- name: 'Clone a copy of Vundle'
  git:
    repo: 'https://github.com/gmarik/Vundle.vim.git'
    dest: '~/.vim/bundle/Vundle.vim'
    force: yes
    update: yes

- name: 'Create directory for all swapfiles'
  file:
    path: '~/.swp'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0700'
    state: 'directory'

- name: 'Symlink ~/.vimrc to managed vimrc'
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: '~/.vimrc'
    state: 'link'
    force: 'yes'

- name: 'Symlink ~/.vim/ftplugin to managed ftplugin'
  file:
    src: "{{ role_path }}/files/ftplugin"
    dest: '~/.vim/ftplugin'
    state: 'link'
    force: 'yes'

- name: 'Create syntax directory'
  file:
    path: '~/.vim/syntax'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0700'
    state: 'directory'

- name: 'Add upstart script syntax file'
  copy:
    src: 'syntax-upstart'
    dest: '~/.vim/syntax/upstart.vim'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0600'

- name: 'Install vim plugins'
  shell: 'vim +PluginInstall +qall'
