---
- name: 'Create the ~/.vim directory'
  file:
    path: '~/.vim'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0700'
    state: directory

- name: 'Create the ~/.vim/bundle directory'
  file:
    path: '~/.vim/bundle'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0700'
    state: directory

- name: 'Clone a copy of Vundle'
  git:
    repo: 'https://github.com/gmarik/Vundle.vim.git'
    dest: '~/.vim/bundle/Vundle.vim'
    force: yes
    update: yes

- name: 'Create directory for all swapfiles'
  file:
    path: '~/.swp'
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0700'
    state: 'directory'


- name: 'Put the vimrc file in place'
  copy:
    src: 'vimrc'
    dest: "~/.vimrc"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'
